version: 2

project_name: anilistgen

before:
  hooks:
    - go mod tidy

builds:
  - id: anilistgen
    main: ./cmd/anilistgen
    binary: anilistgen
    ldflags:
      - -s -w
      - -X main.version={{ .Version }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - id: binary
    formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE*
      - README.md

checksum:
  name_template: checksums.txt

snapshot:
  name_template: "{{ .Version }}-SNAPSHOT-{{ .ShortCommit }}"

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - Merge branch

release:
  github:
    owner: calmcacil
    name: anilistgen
  prerelease: auto
  make_latest: true

dockers:
  - image_templates:
      - "ghcr.io/calmcacil/anilistgen:{{ .Version }}-amd64"
    dockerfile: Dockerfile.goreleaser
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.source=https://github.com/calmcacil/anilistgen"
      - "--build-arg=VERSION={{ .Version }}"
    extra_files:
      - go.mod
      - go.sum

  - image_templates:
      - "ghcr.io/calmcacil/anilistgen:{{ .Version }}-arm64"
    dockerfile: Dockerfile.goreleaser
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.source=https://github.com/calmcacil/anilistgen"
      - "--build-arg=VERSION={{ .Version }}"
    extra_files:
      - go.mod
      - go.sum

docker_manifests:
  - name_template: ghcr.io/calmcacil/anilistgen:{{ .Version }}
    image_templates:
      - ghcr.io/calmcacil/anilistgen:{{ .Version }}-amd64
      - ghcr.io/calmcacil/anilistgen:{{ .Version }}-arm64
  - name_template: ghcr.io/calmcacil/anilistgen:latest
    image_templates:
      - ghcr.io/calmcacil/anilistgen:{{ .Version }}-amd64
      - ghcr.io/calmcacil/anilistgen:{{ .Version }}-arm64
  - name_template: ghcr.io/calmcacil/anilistgen:{{ .Major }}.{{ .Minor }}
    image_templates:
      - ghcr.io/calmcacil/anilistgen:{{ .Version }}-amd64
      - ghcr.io/calmcacil/anilistgen:{{ .Version }}-arm64
