FROM gcr.io/distroless/base-debian12:nonroot

LABEL org.opencontainers.image.source="https://github.com/calmcacil/anilistgen"
LABEL org.opencontainers.image.description="Seasonal anime list generator for MDBList from AniList"

COPY anilistgen /usr/local/bin/anilistgen

ENTRYPOINT ["/usr/local/bin/anilistgen"]
CMD ["daemon"]
