package config

import (
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"time"

	"gopkg.in/yaml.v3"
)

// Config holds the full application configuration loaded from a YAML file.
type Config struct {
	// MDBListAPIKey is the MDBList API key. Can also be set via MDBLIST_API_KEY env var.
	MDBListAPIKey string `yaml:"mdblist_api_key"`

	// Interval is how often to run in daemon mode. 0 means one-shot.
	Interval Duration `yaml:"interval"`

	// AniList settings
	AniList AniListConfig `yaml:"anilist"`

	// MDBList settings
	MDBList MDBListConfig `yaml:"mdblist"`

	// RunOnStart runs a sync immediately on daemon startup. Default: true.
	RunOnStart bool `yaml:"run_on_start"`

	// StateFile is the path to the last-run timestamp file.
	// Used to prevent hammering APIs on rapid container restarts.
	// Default: /tmp/anilistgen.lastrun
	StateFile string `yaml:"state_file"`

	// Logging settings
	Logging LoggingConfig `yaml:"logging"`
}

// AniListConfig holds AniList query settings.
type AniListConfig struct {
	// Year to fetch. 0 means current year. Ignored if Years is set.
	Year int `yaml:"year"`
	// Years is a list of years to process. If set, overrides Year.
	Years []int `yaml:"years"`
	// Seasons to include. Options: "winter", "spring", "summer", "fall", or "all".
	Seasons []string `yaml:"seasons"`
	// MaxPerSeason is the maximum results per season. Default: 100.
	MaxPerSeason int `yaml:"max_per_season"`
	// IncludeONA includes ONA format alongside TV. Default: true.
	IncludeONA bool `yaml:"include_ona"`
	// WinterOverflow merges the previous year's WINTER season into the current
	// WINTER query, capturing shows that premiered in December of the prior year
	// (AniList assigns seasonYear to the calendar year, so December shows are
	// tagged under the previous year). Default: false.
	WinterOverflow bool `yaml:"winter_overflow"`
	// FallbackRelationTypes controls which AniList relation types to follow
	// when a show is not found in MDBList by its direct MAL ID.
	// Only matching relation types are used as fallback.
	// Default: ["PREQUEL", "PARENT"]. Add "ADAPTATION" or "SIDE_STORY" for broader matching.
	FallbackRelationTypes []string `yaml:"fallback_relation_types"`
	// ExcludeTags is a list of AniList tag names to exclude.
	// Shows with any matching tag (case-insensitive) are skipped.
	ExcludeTags []string `yaml:"exclude_tags"`
}

// MDBListConfig holds list creation settings.
type MDBListConfig struct {
	// TitleTemplate supports {season} and {year} placeholders. Default: "Anime {season} {year}".
	TitleTemplate string `yaml:"title_template"`
	// DescriptionTemplate supports {season} and {year}. Default: see DefaultDescriptionTemplate.
	DescriptionTemplate string `yaml:"description_template"`
	// Public sets list visibility. Default: true.
	Public bool `yaml:"public"`
	// Blacklist is a list of show titles or MAL IDs to exclude.
	Blacklist []string `yaml:"blacklist"`
}

// LoggingConfig holds logging settings.
type LoggingConfig struct {
	// Level is one of: debug, info, warn, error. Default: info.
	Level string `yaml:"level"`
	// File path to log file. Empty means stderr.
	File string `yaml:"file"`
}

const (
	// DefaultMaxPerSeason is the default max results per season.
	DefaultMaxPerSeason = 100
	// DefaultTitleTemplate is the default list title template.
	DefaultTitleTemplate = "Anime {season} {year}"
	// DefaultDescriptionTemplate is the default list description template.
	DefaultDescriptionTemplate = "All anime TV series airing in {season} {year}, sourced from AniList. Generated by anilistgen."
	// DefaultInterval is the default daemon interval (24 hours).
	DefaultInterval = 24 * time.Hour
	// DefaultStateFile is where the last-run timestamp is written.
	DefaultStateFile = "/tmp/anilistgen.lastrun"
	// MinInterval is the minimum time between runs (sanity check).
	MinInterval = 1 * time.Hour
)

// Duration is a wrapper for time.Duration that supports YAML string parsing.
type Duration struct {
	time.Duration
}

// UnmarshalYAML parses a duration string like "24h", "30m", etc.
func (d *Duration) UnmarshalYAML(value *yaml.Node) error {
	var s string
	if err := value.Decode(&s); err != nil {
		return err
	}
	dur, err := time.ParseDuration(s)
	if err != nil {
		return fmt.Errorf("invalid duration %q: %w", s, err)
	}
	d.Duration = dur
	return nil
}

// Season resolves the configured season list into AniList season strings.
// Returns ["WINTER", "SPRING", "SUMMER", "FALL"] if "all" is configured.
func (a *AniListConfig) Season() []string {
	if len(a.Seasons) == 0 {
		return AllSeasons()
	}

	seasons := make([]string, 0, len(a.Seasons))
	for _, s := range a.Seasons {
		if strings.EqualFold(s, "all") {
			return AllSeasons()
		}
		switch strings.ToLower(s) {
		case "winter":
			seasons = append(seasons, "WINTER")
		case "spring":
			seasons = append(seasons, "SPRING")
		case "summer":
			seasons = append(seasons, "SUMMER")
		case "fall":
			seasons = append(seasons, "FALL")
		}
	}
	return seasons
}

// AllSeasons returns all four seasons in calendar order.
func AllSeasons() []string {
	return []string{"WINTER", "SPRING", "SUMMER", "FALL"}
}

// YearsOrDefault returns the configured year(s).
// If Years is set, returns it. Otherwise if Year is non-zero, returns [Year].
// Otherwise returns [current year].
func (a *AniListConfig) YearsOrDefault() []int {
	if len(a.Years) > 0 {
		return a.Years
	}
	if a.Year != 0 {
		return []int{a.Year}
	}
	return []int{time.Now().Year()}
}

// FillDefaults sets zero-value fields to their defaults.
func (c *Config) FillDefaults() {
	if c.AniList.MaxPerSeason <= 0 {
		c.AniList.MaxPerSeason = DefaultMaxPerSeason
	}
	if c.AniList.FallbackRelationTypes == nil {
		c.AniList.FallbackRelationTypes = []string{"PREQUEL", "PARENT"}
	}
	if c.MDBList.TitleTemplate == "" {
		c.MDBList.TitleTemplate = DefaultTitleTemplate
	}
	if c.MDBList.DescriptionTemplate == "" {
		c.MDBList.DescriptionTemplate = DefaultDescriptionTemplate
	}
	if c.Interval.Duration == 0 {
		c.Interval.Duration = DefaultInterval
	}
	if c.Logging.Level == "" {
		c.Logging.Level = "info"
	}
}

// Validate checks the config for errors and returns them.
func (c *Config) Validate() error {
	var errs []string

	if c.MDBListAPIKey == "" {
		errs = append(errs, "mdblist_api_key is required (set in config or MDBLIST_API_KEY env var)")
	}

	years := c.AniList.YearsOrDefault()
	for _, y := range years {
		if y < 2000 || y > 2100 {
			errs = append(errs, fmt.Sprintf("anilist year %d is out of range (2000-2100)", y))
		}
	}

	if c.AniList.MaxPerSeason < 1 || c.AniList.MaxPerSeason > 500 {
		errs = append(errs, fmt.Sprintf("anilist.max_per_season %d must be between 1 and 500", c.AniList.MaxPerSeason))
	}

	seasons := c.AniList.Season()
	if len(seasons) == 0 {
		errs = append(errs, "anilist.seasons must specify at least one valid season")
	}

	switch strings.ToLower(c.Logging.Level) {
	case "debug", "info", "warn", "error", "":
		// valid
	default:
		errs = append(errs, fmt.Sprintf("logging.level %q is invalid; must be debug, info, warn, or error", c.Logging.Level))
	}

	if len(errs) > 0 {
		return fmt.Errorf("config validation failed:\n  - %s", strings.Join(errs, "\n  - "))
	}
	return nil
}

// DefaultConfig returns a config with all defaults populated.
func DefaultConfig() *Config {
	return &Config{
		MDBListAPIKey: "",
		Interval:      Duration{Duration: DefaultInterval},
		RunOnStart:    true,
		StateFile:     DefaultStateFile,
		AniList: AniListConfig{
			Year:                  0,
			Years:                 nil,
			Seasons:               []string{"all"},
			MaxPerSeason:          DefaultMaxPerSeason,
			IncludeONA:            true,
			FallbackRelationTypes: []string{"PREQUEL", "PARENT"},
		},
		MDBList: MDBListConfig{
			TitleTemplate:       DefaultTitleTemplate,
			DescriptionTemplate: DefaultDescriptionTemplate,
			Public:              true,
		},
		Logging: LoggingConfig{
			Level: "info",
			File:  "",
		},
	}
}

// envPrefix is the prefix for all environment variable overrides.
const envPrefix = "ALG_"

// applyEnvOverrides checks environment variables and overrides config fields.
// Nested fields use underscore separators: ALG_ANILIST_YEAR, ALG_MDBLIST_PUBLIC, etc.
// List fields (years, seasons, blacklist) use comma-separated values.
func (c *Config) applyEnvOverrides() {
	// MDBList API key — also check legacy MDBLIST_API_KEY
	if v := os.Getenv("ALG_MDBLIST_API_KEY"); v != "" {
		c.MDBListAPIKey = v
	} else if v := os.Getenv("MDBLIST_API_KEY"); v != "" {
		c.MDBListAPIKey = v
	}

	if v := os.Getenv(envPrefix + "INTERVAL"); v != "" {
		if d, err := time.ParseDuration(v); err == nil {
			c.Interval.Duration = d
		}
	}

	if v := os.Getenv(envPrefix + "ANILIST_YEAR"); v != "" {
		if y, err := strconv.Atoi(v); err == nil && y >= 0 {
			c.AniList.Year = y
		}
	}

	if v := os.Getenv(envPrefix + "ANILIST_YEARS"); v != "" {
		parts := strings.Split(v, ",")
		var years []int
		for _, p := range parts {
			p = strings.TrimSpace(p)
			if p == "" {
				continue
			}
			if y, err := strconv.Atoi(p); err == nil && y > 0 {
				years = append(years, y)
			}
		}
		if len(years) > 0 {
			c.AniList.Years = years
		}
	}

	if v := os.Getenv(envPrefix + "ANILIST_SEASONS"); v != "" {
		parts := strings.Split(v, ",")
		for i, p := range parts {
			parts[i] = strings.TrimSpace(p)
		}
		c.AniList.Seasons = parts
	}

	if v := os.Getenv(envPrefix + "ANILIST_MAX_PER_SEASON"); v != "" {
		if max, err := strconv.Atoi(v); err == nil && max > 0 {
			c.AniList.MaxPerSeason = max
		}
	}

	if v := os.Getenv(envPrefix + "ANILIST_INCLUDE_ONA"); v != "" {
		c.AniList.IncludeONA = v == "1" || strings.EqualFold(v, "true")
	}

	if v := os.Getenv(envPrefix + "ANILIST_WINTER_OVERFLOW"); v != "" {
		c.AniList.WinterOverflow = v == "1" || strings.EqualFold(v, "true")
	}

	if v := os.Getenv(envPrefix + "ANILIST_FALLBACK_RELATIONS"); v != "" {
		parts := strings.Split(v, ",")
		for i, p := range parts {
			parts[i] = strings.TrimSpace(p)
		}
		c.AniList.FallbackRelationTypes = parts
	}

	if v := os.Getenv(envPrefix + "ANILIST_EXCLUDE_TAGS"); v != "" {
		parts := strings.Split(v, ",")
		for i, p := range parts {
			parts[i] = strings.TrimSpace(p)
		}
		c.AniList.ExcludeTags = parts
	}

	if v := os.Getenv(envPrefix + "MDBLIST_TITLE_TEMPLATE"); v != "" {
		c.MDBList.TitleTemplate = v
	}

	if v := os.Getenv(envPrefix + "MDBLIST_DESCRIPTION_TEMPLATE"); v != "" {
		c.MDBList.DescriptionTemplate = v
	}

	if v := os.Getenv(envPrefix + "MDBLIST_PUBLIC"); v != "" {
		c.MDBList.Public = v == "1" || strings.EqualFold(v, "true")
	}

	if v := os.Getenv(envPrefix + "MDBLIST_BLACKLIST"); v != "" {
		parts := strings.Split(v, ",")
		for i, p := range parts {
			parts[i] = strings.TrimSpace(p)
		}
		c.MDBList.Blacklist = parts
	}

	if v := os.Getenv(envPrefix + "LOG_LEVEL"); v != "" {
		c.Logging.Level = v
	}

	if v := os.Getenv(envPrefix + "LOG_FILE"); v != "" {
		c.Logging.File = v
	}

	if v := os.Getenv(envPrefix + "RUN_ON_START"); v != "" {
		c.RunOnStart = v == "1" || strings.EqualFold(v, "true")
	}

	if v := os.Getenv(envPrefix + "STATE_FILE"); v != "" {
		c.StateFile = v
	}
}

// Load reads a config from the given path. If path is empty, it searches
// default locations: ./anilistgen.yaml, $XDG_CONFIG_HOME/anilistgen/anilistgen.yaml
func Load(path string) (*Config, string, error) {
	paths := searchPaths(path)

	for _, p := range paths {
		cfg, err := loadFile(p)
		if err != nil {
			if os.IsNotExist(err) {
				continue
			}
			return nil, "", fmt.Errorf("config error in %s: %w", p, err)
		}
		cfg.FillDefaults()
		cfg.applyEnvOverrides()
		return cfg, p, nil
	}

	// No config file found — fall back to defaults + env var overrides.
	// This allows pure-env-var usage (Docker, etc.) without a config file.
	cfg := DefaultConfig()
	cfg.applyEnvOverrides()
	return cfg, "", nil
}

// loadFile reads and parses a single YAML config file.
func loadFile(path string) (*Config, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()

	// First decode into a raw map to detect unknown keys
	var raw map[string]any
	decoder := yaml.NewDecoder(f)
	if err := decoder.Decode(&raw); err != nil {
		return nil, fmt.Errorf("parse %s: %w", path, err)
	}

	// Check for known top-level keys
	knownKeys := map[string]bool{
		"mdblist_api_key": true,
		"interval":        true,
		"run_on_start":    true,
		"state_file":      true,
		"anilist":         true,
		"mdblist":         true,
		"logging":         true,
	}
	for k := range raw {
		if !knownKeys[k] {
			// Cannot use slog here because logging isn't set up yet
			fmt.Fprintf(os.Stderr, "warning: config file %s contains unknown key %q\n", path, k)
		}
	}

	// Re-encode back to YAML bytes and decode into the struct
	// This gives us proper struct validation
	data, err := yaml.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("re-marshal config: %w", err)
	}

	var cfg Config
	if err := yaml.Unmarshal(data, &cfg); err != nil {
		return nil, fmt.Errorf("parse %s: %w", path, err)
	}

	return &cfg, nil
}

// searchPaths returns the ordered list of config file paths to search.
func searchPaths(cliPath string) []string {
	if cliPath != "" {
		return []string{cliPath}
	}

	paths := []string{filepath.Join(".", "anilistgen.yaml")}

	xdg := os.Getenv("XDG_CONFIG_HOME")
	if xdg == "" {
		home, err := os.UserHomeDir()
		if err == nil {
			xdg = filepath.Join(home, ".config")
		}
	}
	if xdg != "" {
		paths = append(paths, filepath.Join(xdg, "anilistgen", "anilistgen.yaml"))
	}

	return paths
}

// WriteDefaultConfig writes a default config file with inline documentation to the given path.
func WriteDefaultConfig(path string) error {
	content := `# anilistgen configuration
# See https://github.com/calmcacil/anilistgen for full documentation.

# MDBList API key (required). Can also be set via MDBLIST_API_KEY env var.
mdblist_api_key: ""

# How often to run in daemon mode. Parsed as Go duration (e.g. "24h", "12h").
# Set to "0" for one-shot mode. Default: 24h
interval: "24h"

# AniList query settings
anilist:
  # Year to fetch. 0 means current year. Ignored if 'years' is set.
  year: 0

  # Years to fetch (overrides 'year' above). Uncomment for multiple years:
  # years:
  #   - 2026
  #   - 2027

  # Seasons to include. Options: winter, spring, summer, fall, or "all".
  # Default: all
  seasons:
    - all

  # Maximum results per season from AniList. Default: 100
  max_per_season: 100

  # Include ONA format alongside TV. Default: true
  include_ona: true

  # Merge December-premiering shows from the previous year into WINTER.
  # When enabled, fetches the prior year's WINTER and merges only
  # shows that started in December (startDate.month == 12). AniList
  # assigns calendar year to seasonYear, so a December-premiering show
  # is tagged under the prior year but belongs in the current winter
  # viewing list. Disable if you want WINTER to contain only Jan-Mar
  # premieres. Default: true
  winter_overflow: true

  # Fallback relation types to follow when a show's MAL ID isn't found
  # in MDBList database. The tool follows the relation chain (e.g. via
  # PREQUEL) to find a parent series that MDBList has indexed.
  # Default: ["PREQUEL", "PARENT"]
  # fallback_relation_types:
  #   - PREQUEL
  #   - PARENT

  # AniList content tags to exclude. Shows with any matching tag
  # (case-insensitive comparison) are skipped entirely. Useful for
  # filtering out specific content categories.
  # exclude_tags:
  #   - "Hentai"
  #   - "Guro"

# MDBList list settings
mdblist:
  # List title template. Supports {season} and {year} placeholders.
  # Default: "Anime {season} {year}"
  title_template: "Anime {season} {year}"

  # List description template. Supports {season} and {year}.
  # Default: "All anime TV series airing in {season} {year}, sourced from AniList. Generated by anilistgen."
  description_template: "All anime TV series airing in {season} {year}, sourced from AniList. Generated by anilistgen."

  # Set to false to create private lists. Default: true
  public: true

  # Note: MDBList's free plan limits you to 4 static lists total.
  # If you sync 4 seasons x 2 years = 8 lists, you'll hit this limit
  # and need to delete old lists or upgrade your MDBList plan.

  # Blacklist: shows to skip. Can be exact titles or MAL IDs.
  # Matched case-insensitively as substrings. Examples:
  # blacklist:
  #   - "Sentenced to Be a Hero"    # skip by title
  #   - 57658                        # skip by MAL ID
  #   - "One Piece"                  # skip any title containing "One Piece"

# Logging
logging:
  # One of: debug, info, warn, error. Default: info
  level: info

  # Path to log file. Empty means stderr.
  file: ""

# Daemon behavior
# Run a sync immediately on startup. Default: true
run_on_start: true

# Path for last-run timestamp (sanity check against rapid restarts).
# Default: /tmp/anilistgen.lastrun
state_file: /tmp/anilistgen.lastrun
`

	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("create config directory %s: %w", dir, err)
	}

	if err := os.WriteFile(path, []byte(content), 0600); err != nil {
		return fmt.Errorf("write config to %s: %w", path, err)
	}

	return nil
}

// ResolveConfigPath returns the path where init-config should write, given a CLI flag value.
func ResolveConfigPath(cliPath string) string {
	if cliPath != "" {
		return cliPath
	}

	// Check if any default path already has a file
	paths := searchPaths("")
	for _, p := range paths {
		if _, err := os.Stat(p); err == nil {
			return p
		}
	}

	// Default to XDG config home
	xdg := os.Getenv("XDG_CONFIG_HOME")
	if xdg == "" {
		home, _ := os.UserHomeDir()
		xdg = filepath.Join(home, ".config")
	}
	return filepath.Join(xdg, "anilistgen", "anilistgen.yaml")
}
